#!/usr/env bash

rm -rf ~/.vimrc
rm -rf ~/.vim/bundle

# Setup Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install vim plugins
cd ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git
git clone git@github.com:tomtom/tcomment_vim.git
