#!/usr/bin/env bash

rm -rf ~/.vimrc
rm -rf ~/.vim/bundle

# Setup Pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install vim plugins
cd ~/.vim/bundle
git clone git@github.com:tpope/vim-sensible.git
git clone https://github.com/scrooloose/nerdtree.git
git clone git@github.com:tomtom/tcomment_vim.git
git clone git@github.com:kien/ctrlp.vim.git
git clone git@github.com:ervandew/supertab.git

curl https://raw.githubusercontent.com/BrandonMathis/tamevim/master/vimrc > ~/.vimrc
