#!/usr/bin/env bash

USER_NAME=ubuntu
SSH_DIR=/home/$USER_NAME/.ssh

# Basic Setup
apt-get update
echo '$EDITOR=vim' > ~/.bashrc

# Create User
adduser --disabled-password --gecos "" $USER_NAME
echo "$USER_NAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers

# SSH
if [[ ! -e $SSH_DIR ]]; then
  echo "creating $SSH_DIR"
  mkdir $SSH_DIR
  echo "ensuring ownsership of $SSH_DIR"
  chown -R $USER_NAME:$USER_NAME $SSH_DIR
  echo "filling $SSH_DIR/authorized_keys with public key"
  cat ~/.ssh/authorized_keys > $SSH_DIR/authorized_keys
elif [[ ! -d $SSH_DIR ]]; then
  echo "$SSH_DIR already exists... skipping"
fi


# Disbale Root SSH
if [ "$SSH_DIR/authorized_keys" = "$HOME/.ssh/authorized_keys" ]; then
  echo "Clearing public key from $HOME/.ssh"
  echo '' > $HOME/.ssh/authorized_keys
fi
